services:
    ankerctl:
        container_name: ankerctl
        restart: unless-stopped
        build: .

        # host-mode networking is required for pppp communication with the
        # printer, since it is an asymmetrical udp protocol.
        network_mode: host

        # bind to all interfaces to allow remote access via SSH
        environment:
            - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
            - FLASK_PORT=${FLASK_PORT:-4470}
        volumes:
            - ./ankerctl_data:/root/.config/ankerctl
